/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Novandi Ramadhan
 */
public class ConnectOVO extends javax.swing.JFrame {
    int xx = 0;
    int yy = 0;
    Connection con;
    Statement stat;
    PreparedStatement ps;
    ResultSet rs;
    String sql, userLogin;
    
    /**
     * Creates new form ConnectOVO
     */
    public ConnectOVO() {
        initComponents();
        checkField();
        
        Config DB = new Config();
        DB.connect();
        con = DB.conn;
        stat = DB.stm;
    }
    
    public void connectOvo(String username) {
        userLogin = username;
    }
    
    private void checkField() {
        fieldNum.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                changed();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                changed();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                changed();
            }

            public void changed() {
                if(fieldNum.getText().equals("")) {
                     fieldNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,0,0)));
                     alertNum.setText("Nomor telepon OVO harus diisi");
                 } else if(fieldNum.getText().length() < 12) {
                     fieldNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,0,0)));
                     alertNum.setText("Nomor telepon OVO minimal 12 angka");
                 } else {
                     if((fieldNum.getText()).matches("[0-9]+")) {
                         alertNum.setText("");
                         fieldNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

                     } else {
                         alertNum.setText("Nomor telepon OVO harus dalam bentuk angka");
                         fieldNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,0,0)));
                     }
                 }
             }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ovoPanel = new javax.swing.JPanel();
        closeWindow = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldNum = new javax.swing.JTextField();
        alertNum = new javax.swing.JLabel();
        btnNum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(424, 568));
        setUndecorated(true);
        setResizable(false);

        ovoPanel.setBackground(new java.awt.Color(255, 255, 255));
        ovoPanel.setForeground(new java.awt.Color(0, 0, 0));
        ovoPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ovoPanelMouseDragged(evt);
            }
        });
        ovoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ovoPanelMousePressed(evt);
            }
        });

        closeWindow.setBackground(new java.awt.Color(255, 255, 255));
        closeWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeWindow.setIcon(new javax.swing.ImageIcon("D:\\Project\\Java\\GUI\\NikeShop\\src\\assets\\cancel.png")); // NOI18N
        closeWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        closeWindow.setOpaque(true);
        closeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeWindowMouseExited(evt);
            }
        });

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon("D:\\Project\\Java\\GUI\\NikeShop\\src\\assets\\minus.png")); // NOI18N
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Project\\Java\\GUI\\NikeShop\\src\\assets\\ovo-logo.png")); // NOI18N

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Masukkan nomor OVO kamu");

        fieldNum.setBackground(new java.awt.Color(255, 255, 255));
        fieldNum.setFont(new java.awt.Font("Google Sans", 0, 24)); // NOI18N
        fieldNum.setForeground(new java.awt.Color(0, 0, 0));
        fieldNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        alertNum.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        alertNum.setForeground(new java.awt.Color(204, 0, 0));

        btnNum.setBackground(new java.awt.Color(76, 52, 148));
        btnNum.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        btnNum.setForeground(new java.awt.Color(255, 255, 255));
        btnNum.setText("SAMBUNGKAN");
        btnNum.setBorder(null);
        btnNum.setContentAreaFilled(false);
        btnNum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNum.setOpaque(true);
        btnNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNumMouseExited(evt);
            }
        });
        btnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(alertNum)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldNum))
                        .addGap(69, 69, 69))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(fieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btnNum, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout ovoPanelLayout = new javax.swing.GroupLayout(ovoPanel);
        ovoPanel.setLayout(ovoPanelLayout);
        ovoPanelLayout.setHorizontalGroup(
            ovoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ovoPanelLayout.createSequentialGroup()
                .addGap(270, 344, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(closeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ovoPanelLayout.setVerticalGroup(
            ovoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ovoPanelLayout.createSequentialGroup()
                .addGroup(ovoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize)
                    .addComponent(closeWindow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ovoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ovoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closeWindowMouseClicked

    private void closeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseEntered
        closeWindow.setBackground(new java.awt.Color(204, 204, 204));
        closeWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 10));
    }//GEN-LAST:event_closeWindowMouseEntered

    private void closeWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseExited
        closeWindow.setBackground(new java.awt.Color(255, 255, 255));
        closeWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
    }//GEN-LAST:event_closeWindowMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(new java.awt.Color(204, 204, 204));
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 10));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
    }//GEN-LAST:event_minimizeMouseExited

    private void btnNumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumMouseEntered
        btnNum.setBackground(new java.awt.Color(93, 65, 176));
    }//GEN-LAST:event_btnNumMouseEntered

    private void btnNumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumMouseExited
        btnNum.setBackground(new java.awt.Color(76,52,148));
    }//GEN-LAST:event_btnNumMouseExited

    private void btnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumActionPerformed
        btnNum.setBackground(new java.awt.Color(57, 36, 117));
        
        try {
            sql = "SELECT no_ovo FROM ovo WHERE no_ovo = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, fieldNum.getText());
            rs = ps.executeQuery();
            boolean ovoExists = false;
            while(rs.next()) {
                ovoExists = true;
            }
            
            if(ovoExists) {
                sql = "SELECT o.no_ovo, u.no_ovo FROM ovo o JOIN users u ON u.no_ovo = o.no_ovo WHERE o.no_ovo = ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, fieldNum.getText());
                rs = ps.executeQuery();
                boolean ovoUse = false;
                while(rs.next()) {
                    ovoUse = true;
                }
                
                if(ovoUse) {
                    fieldNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,0,0)));
                    alertNum.setText("Nomor telepon sudah dipakai oleh pengguna lain di NikeShop");
                } else {
                    this.setVisible(false);
                    PinOVO pinO = new PinOVO();
                    pinO.checkPin(userLogin, fieldNum.getText());
                    pinO.setVisible(true);
                }
            } else {
                fieldNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,0,0)));
                alertNum.setText("Nomor telepon tidak ditemukan");
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnNumActionPerformed

    private void ovoPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ovoPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_ovoPanelMouseDragged

    private void ovoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ovoPanelMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_ovoPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectOVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConnectOVO().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertNum;
    private javax.swing.JButton btnNum;
    private javax.swing.JLabel closeWindow;
    private javax.swing.JTextField fieldNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel ovoPanel;
    // End of variables declaration//GEN-END:variables
}
