/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Novandi Ramadhan
 */
public class Register extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    int xx = 0;
    int yy = 0;
    private static final String email_pattern = 
    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("../assets/jordan.png")).getImage());
        
        Config DB = new Config();
        DB.connect();
        con = DB.conn;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterForm = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        closeWindow = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        toSignin = new javax.swing.JLabel();
        alertUsername = new javax.swing.JLabel();
        alertPassword = new javax.swing.JLabel();
        alertCheck = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        alertEmail = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        alertName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        RegisterForm.setBackground(new java.awt.Color(255, 255, 255));
        RegisterForm.setForeground(new java.awt.Color(0, 0, 0));
        RegisterForm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                RegisterFormMouseDragged(evt);
            }
        });
        RegisterForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterFormMousePressed(evt);
            }
        });

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("D:\\Project\\Java\\GUI\\NikeShop\\src\\assets\\logo-2x.png")); // NOI18N

        title.setFont(new java.awt.Font("Google Sans", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("BE THE FIRST TO KNOW");

        closeWindow.setBackground(new java.awt.Color(255, 255, 255));
        closeWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeWindow.setIcon(new javax.swing.ImageIcon("D:\\Project\\Java\\GUI\\NikeShop\\src\\assets\\cancel.png")); // NOI18N
        closeWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        closeWindow.setOpaque(true);
        closeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeWindowMouseExited(evt);
            }
        });

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon("D:\\Project\\Java\\GUI\\NikeShop\\src\\assets\\minus.png")); // NOI18N
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        subtitle.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        subtitle.setForeground(new java.awt.Color(102, 102, 102));
        subtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitle.setText("Register your account");

        username.setBackground(new java.awt.Color(240, 240, 240));
        username.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(51, 51, 51));
        passwordLabel.setText("Password");

        password.setBackground(new java.awt.Color(240, 240, 240));
        password.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 0, 0));
        submit.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Sign Up");
        submit.setBorder(null);
        submit.setBorderPainted(false);
        submit.setContentAreaFilled(false);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.setOpaque(true);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel7.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Already have an account?");

        toSignin.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        toSignin.setForeground(new java.awt.Color(51, 102, 255));
        toSignin.setText("Sign In");
        toSignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toSigninMouseClicked(evt);
            }
        });

        alertUsername.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        alertUsername.setForeground(new java.awt.Color(255, 0, 51));

        alertPassword.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        alertPassword.setForeground(new java.awt.Color(255, 0, 51));

        alertCheck.setBackground(new java.awt.Color(255, 0, 51));
        alertCheck.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        alertCheck.setForeground(new java.awt.Color(255, 255, 255));
        alertCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 0));
        alertCheck.setOpaque(true);

        email.setBackground(new java.awt.Color(240, 240, 240));
        email.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("Email");

        alertEmail.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        alertEmail.setForeground(new java.awt.Color(255, 0, 51));

        fullname.setBackground(new java.awt.Color(240, 240, 240));
        fullname.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        fullname.setForeground(new java.awt.Color(0, 0, 0));
        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        fullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullnameKeyTyped(evt);
            }
        });

        usernameLabel1.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(51, 51, 51));
        usernameLabel1.setText("Full Name");

        alertName.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        alertName.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout RegisterFormLayout = new javax.swing.GroupLayout(RegisterForm);
        RegisterForm.setLayout(RegisterFormLayout);
        RegisterFormLayout.setHorizontalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegisterFormLayout.createSequentialGroup()
                .addComponent(subtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel1)
                    .addComponent(emailLabel)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterFormLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toSignin))
                    .addGroup(RegisterFormLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(closeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fullname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(alertCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                        .addComponent(alertUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alertPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                        .addComponent(alertEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alertName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(RegisterFormLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterFormLayout.setVerticalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterFormLayout.createSequentialGroup()
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize)
                    .addComponent(closeWindow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo)
                .addGap(6, 6, 6)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterFormLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(subtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertCheck)
                .addGap(18, 18, 18)
                .addComponent(usernameLabel1)
                .addGap(4, 4, 4)
                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alertName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addGap(4, 4, 4)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertUsername)
                .addGap(8, 8, 8)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLabel)
                .addGap(4, 4, 4)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertEmail)
                .addGap(28, 28, 28)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(toSignin))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeWindowMouseClicked

    private void closeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseEntered
        closeWindow.setBackground(new java.awt.Color(204, 204, 204));
        closeWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 10));
    }//GEN-LAST:event_closeWindowMouseEntered

    private void closeWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseExited
        closeWindow.setBackground(new java.awt.Color(255, 255, 255));
        closeWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
    }//GEN-LAST:event_closeWindowMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(new java.awt.Color(204, 204, 204));
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 10));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
    }//GEN-LAST:event_minimizeMouseExited

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        if(username.getText().equals("")) {
            alertUsername.setText("Username harus diisi");
            username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
        } else {
            alertUsername.setText("");
            username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240,240,240), 2));
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        if(String.valueOf(password.getPassword()).equals("")) {
            alertPassword.setText("Username harus diisi");
            password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
        } else {
            alertPassword.setText("");
            password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240,240,240), 2));
        }
    }//GEN-LAST:event_passwordKeyTyped

    private String hashPassword(String password) throws NoSuchAlgorithmException, InvalidKeySpecException {
        int iterations = 1000;
        char[] chars = password.toCharArray();
        byte[] salt = getSalt();

        PBEKeySpec spec = new PBEKeySpec(chars, salt, iterations, 64 * 8);
        SecretKeyFactory skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");

        byte[] hash = skf.generateSecret(spec).getEncoded();
        return iterations + ":" + toHex(salt) + ":" + toHex(hash);
    }
    
    private byte[] getSalt() throws NoSuchAlgorithmException {
        SecureRandom sr = SecureRandom.getInstance("SHA1PRNG");
        byte[] salt = new byte[16];
        sr.nextBytes(salt);
        return salt;
    }
    
    private String toHex(byte[] array) {
        BigInteger bi = new BigInteger(1, array);
        String hex = bi.toString(16);

        int paddingLength = (array.length * 2) - hex.length();
        if(paddingLength > 0) {
            return String.format("%0"  +paddingLength + "d", 0) + hex;
        } else {
            return hex;
        }
    }
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if((!username.getText().equals("") && !String.valueOf(password.getPassword()).equals("")) && 
           (!fullname.getText().equals("") && !email.getText().equals(""))) 
        {
            if(email.getText().matches(email_pattern)) {
                alertName.setText("");
                alertUsername.setText("");
                alertPassword.setText("");
                alertEmail.setText("");
                fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
                username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
                password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
                email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));

                try {
                    stat = con.createStatement();
                    String passHashed = hashPassword(String.valueOf(password.getPassword()));
                    
                    stat.executeUpdate("INSERT INTO users(fullname, username, password, email, address, no_telp, saldo, no_ovo) VALUES('" 
                            + fullname.getText() + "','" 
                            + username.getText() + "','" 
                            + passHashed + "','" 
                            + email.getText() + "', '', '', 0, '')");

                    alertCheck.setText("Berhasil daftar akun! silahkan login.");
                    alertCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 10));
                    alertCheck.setBackground(new java.awt.Color(0, 204, 51));

                    fullname.setText("");
                    username.setText("");
                    password.setText("");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                } catch (NoSuchAlgorithmException | InvalidKeySpecException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            } else {
                alertEmail.setText("Format email tidak valid");
                email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
            }
        } else {
            if(fullname.getText().equals("")) {
                alertName.setText("Username harus diisi");
                fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
            } else {
                alertName.setText("");
                alertName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
            }
            
            if(username.getText().equals("")) {
                alertName.setText("Username harus diisi");
                alertName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
            } else {
                alertName.setText("");
                alertName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
            }
            
            if(String.valueOf(password.getPassword()).equals("")) {
                alertPassword.setText("Password harus diisi");
                password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
            } else {
                alertPassword.setText("");
                password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
            }
            
            if(email.getText().equals("")) {
                alertEmail.setText("Email harus diisi");
                email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
            } else if(!email.getText().matches(email_pattern)) {
                alertEmail.setText("Format email tidak valid");
                email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
            } else {
                alertEmail.setText("");
                email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240,240,240), 2));
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void toSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toSigninMouseClicked
        this.setVisible(false);
        Login loginUI = new Login();
        loginUI.setVisible(true);
    }//GEN-LAST:event_toSigninMouseClicked

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        if(email.getText().equals("")) {
            alertEmail.setText("Email harus diisi");
            email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
        } else if(!email.getText().matches(email_pattern)) {
            alertEmail.setText("Format email tidak valid");
            email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
        } else {
            alertEmail.setText("");
            email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240,240,240), 2));
        }
    }//GEN-LAST:event_emailKeyTyped

    private void fullnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullnameKeyTyped
        if(fullname.getText().equals("")) {
            alertName.setText("Username harus diisi");
            fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,51), 2));
        } else {
            alertName.setText("");
            fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240,240,240), 2));
        }
    }//GEN-LAST:event_fullnameKeyTyped

    private void RegisterFormMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterFormMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_RegisterFormMouseDragged

    private void RegisterFormMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterFormMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_RegisterFormMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegisterForm;
    private javax.swing.JLabel alertCheck;
    private javax.swing.JLabel alertEmail;
    private javax.swing.JLabel alertName;
    private javax.swing.JLabel alertPassword;
    private javax.swing.JLabel alertUsername;
    private javax.swing.JLabel closeWindow;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submit;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    private javax.swing.JLabel toSignin;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
